import type { BaseButton } from "./BaseButton.extras";
import type { Button } from "./Button.extras";
import type { ButtonsGroup } from "./ButtonsGroup.extras";
import type { Card } from "./Card.extras";
import type { CardActions } from "./CardActions.extras";
import type { CardSection } from "./CardSection.extras";
import type { DatetimePicker } from "./DatetimePicker.extras";
import type { Droppable } from "./Droppable.extras";
import type { ExpansionItem } from "./ExpansionItem.extras";
import type { Form } from "./Form.extras";
import type { FormActions } from "./FormActions.extras";
import type { FormButton } from "./FormButton.extras";
import type { FormSection } from "./FormSection.extras";
import type { Group } from "./Group.extras";
import type { IconButton } from "./IconButton.extras";
import type { IconButtonsGroup } from "./IconButtonsGroup.extras";
import type { IconPicker } from "./IconPicker.extras";
import type { Indent } from "./Indent.extras";
import type { Input } from "./Input.extras";
import type { Item } from "./Item.extras";
import type { Knob } from "./Knob.extras";
import type { LanguagePicker } from "./LanguagePicker.extras";
import type { Menu } from "./Menu.extras";
import type { MenuItem } from "./MenuItem.extras";
import type { NumericInput } from "./NumericInput.extras";
import type { OptionGroup } from "./OptionGroup.extras";
import type { PageLayout } from "./PageLayout.extras";
import type { PageSection } from "./PageSection.extras";
import type { PopupProxy } from "./PopupProxy.extras";
import type { Resizer } from "./Resizer.extras";
import type { Section } from "./Section.extras";
import type { Select } from "./Select.extras";
import type { Sortable } from "./Sortable.extras";
import type { Subsection } from "./Subsection.extras";
import type { Switchable } from "./Switchable.extras";
import type { Table } from "./Table.extras";
import type { TimeInput } from "./TimeInput.extras";
import type { Toggle } from "./Toggle.extras";
import type { Tooltip } from "./Tooltip.extras";

declare module "@vue/runtime-core" {
  interface GlobalComponents {
    readonly "m-base-button": BaseButton.Global;
    readonly "m-button": Button.Global;
    readonly "m-buttons-group": ButtonsGroup.Global;
    readonly "m-card": Card.Global;
    readonly "m-card-actions": CardActions.Global;
    readonly "m-card-section": CardSection.Global;
    readonly "m-datetime-picker": DatetimePicker.Global;
    readonly "m-dialog": PopupProxy.Global;
    readonly "m-droppable": Droppable.Global;
    readonly "m-expansion-item": ExpansionItem.Global;
    readonly "m-form": Form.Global;
    readonly "m-form-actions": FormActions.Global;
    readonly "m-form-button": FormButton.Global;
    readonly "m-form-section": FormSection.Global;
    readonly "m-group": Group.Global;
    readonly "m-icon-button": IconButton.Global;
    readonly "m-icon-buttons-group": IconButtonsGroup.Global;
    readonly "m-icon-picker": IconPicker.Global;
    readonly "m-indent": Indent.Global;
    readonly "m-input": Input.Global;
    readonly "m-item": Item.Global;
    readonly "m-knob": Knob.Global;
    readonly "m-language-picker": LanguagePicker.Global;
    readonly "m-menu": Menu.Global;
    readonly "m-menu-item": MenuItem.Global;
    readonly "m-numeric-input": NumericInput.Global;
    readonly "m-option-group": OptionGroup.Global;
    readonly "m-page-layout": PageLayout.Global;
    readonly "m-page-section": PageSection.Global;
    readonly "m-resizer": Resizer.Global;
    readonly "m-section": Section.Global;
    readonly "m-select": Select.Global;
    readonly "m-sortable": Sortable.Global;
    readonly "m-subsection": Subsection.Global;
    readonly "m-switchable": Switchable.Global;
    readonly "m-table": Table.Global;
    readonly "m-time-input": TimeInput.Global;
    readonly "m-toggle": Toggle.Global;
    readonly "m-tooltip": Tooltip.Global;
  }
}
